name: try_jinja
description: Play with the jinja package
version: 0.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: any
  jinja: ^0.2.0

dev_dependencies:
  pedantic: ^1.8.0

publish_to: none
