name: try_moor
description: A simple command-line application.

environment:
  sdk: '>=2.7.0 <3.0.0'
  
dependencies:
  path: ^1.6.0
  moor: ^3.0.2
  moor_ffi: ^0.5.0
  sqflite: any
  
dev_dependencies:
  pedantic: ^1.8.0
  moor_generator: ^3.0.0
  build_runner: any

