name: unit_testing_intro
description: A simple command-line application.
version: 0.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.6.0

dev_dependencies:
  test: any

publish_to: none
