name: todo_reporter_generator
description: A simple command-line application.
version: 0.0.2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: 0.38.2
  build: '>=0.12.0 <2.0.0'  
  source_gen: ^0.9.0 
  todo_reporter:
    path: ../todo_reporter/
  
dev_dependencies:
  analyzer: 0.38.2
  build_test: ^0.10.0  
  build_runner: '>=0.9.0 <0.11.0'  
  test: ^1.0.0

dependency_overrides:
 
