name: todo_reporter_generator
description: A simple command-line application.
version: 0.0.3

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ">=0.37.0 <0.40.0"
  build: ^1.3.0
  source_gen: ^0.9.0
  todo_reporter:
    path: ../todo_reporter/
  
dev_dependencies:
  source_gen: ^0.9.0

 
