name: try_uuid
description: A simple command-line application.
version: 0.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  uuid: 2.1.0

dev_dependencies:
  pedantic: ^1.8.0

publish_to: none
